### PR TITLE
New features, fixes and documentation

### PR DESCRIPTION
**Pull request by SamCourse**
## Summary
This includes a lot of new features, changes to match target organization, bug fixes and documentation updates to reflect the changes made.

## Changes
- Added issue templates
- Added new Dutch translations, removed French and Portuguese
- Update app to match target organization theme and logos
- Added dependabot
- Fixed issues with imports and invalid hook call constraints
- Added recommended mediator to the readme

### CODE REVIEW

**Comment by AnonymousWP** [comment]
Could you please add headers in the description? Such as 'Added', 'Changes' and 'Fixes' for example. This makes me think whether I should add a PR-template to repos or not.

**Comment by SamCourse** [comment]
Updated the description, is this satisfactory? @AnonymousWP

**Comment by AnonymousWP** [comment]
Yes, much better, thanks. Would be nice to create a new release when dev gets merged with main. Then, GitHub can also automatically generate the changelog per release.

**Comment by SamCourse** [comment]
Sounds like a great idea for a new issue! 😁

**Comment by AnonymousWP** [comment]
> Sounds like a great idea for a new issue! 😁

On it. :)

**Review by Jaimy0 — APPROVED** [review]
LGTM!👍

**Pull request merged**
